# Copyright (C) 2024 Toitware ApS.
#
# Use of this source code is governed by a BSD0-style license that can be
# found in the LICENSE file.

name: Build

on:
  push

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Toit build environment
        uses: ./toit/actions/setup-build
        with:
          toit-dir: toit
          esp32: true

      - name: Build
        shell: bash
        run: |
          make init  # Can be removed once the project is set up.
          make
